# Application classes that will be serialized/deserialized over Gson
-keep class com.aspectsense.pharmacyguidecy.data.City { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.Locality { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.Pharmacy { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.OnCall { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.Place { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.DateToPharmacy { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.UpdateResponse { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.FlatPharmacy { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.FlatPharmacyAsStructuredData { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.Address { <fields>; }
-keep class com.aspectsense.pharmacyguidecy.data.Geo { <fields>; }
